const CIRCLE_SIZE = 60;
const STROKE_WIDTH = 2;
const RADIUS = (CIRCLE_SIZE - STROKE_WIDTH) / 2;
const CIRCUMFERENCE = 2 * Math.PI * RADIUS;
const ACTIVE_COLOR = '#0381FF';
const INACTIVE_COLOR = '#666666';

export {
  CIRCLE_SIZE,
  STROKE_WIDTH,
  RADIUS,
  CIRCUMFERENCE,
  ACTIVE_COLOR,
  INACTIVE_COLOR,
};
